### ISSUE TITLE
Pin 'PA4' is not a valid pin name on mcu 'adxl'

### ISSUE THREAD

**Issue by plano-harry** [xbst/KUSBA#15]
Error message from from klipper.  

configparser.Error: Include file '/home/quadra/printer_data/config/adxlmcu.cfg' does not exist
__... so I added the adxlmcu code into printer.cfg manually - then the following error occurred ...._

Extruder max_extrude_ratio=0.266081
mcu 'mcu': Starting serial connect
webhooks client 281473353273600: New connection
webhooks client 281473353273600: Client info {'program': 'Moonraker', 'version': 'v0.8.0-29-g80920dd'}
Loaded MCU 'mcu' 117 commands (v0.11.0-121-ga5fb2076 / gcc: (15:8-2019-q3-1+b1) 8.3.1 20190703 (release) [gcc-8-branch revision 273027] binutils: (2.35.2-2+14+b2) 2.35.2)
MCU 'mcu' config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_i2c3=PA8,PC9 BUS_PINS_sdio=PC12,PD2,PC8,PC9,PC10,PC11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi2a=PC2,PC3,PB10 BUS_PINS_spi3=PB4,PB5,PB3 BUS_PINS_spi3a=PC11,PC12,PC10 BUS_PINS_spi4=PE13,PE14,PE12 CLOCK_FREQ=84000000 MCU=stm32f401xc PWM_MAX=255 RECEIVE_WINDOW=192 RESERVE_PINS_crystal=PH0,PH1 RESERVE_PINS_serial=PA10,PA9 SERIAL_BAUD=250000 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
mcu 'adxl': Starting serial connect
Loaded MCU 'adxl' 105 commands (v0.11.0-127-g4b1536d6 / gcc: (15:8-2019-q3-1+b1) 8.3.1 20190703 (release) [gcc-8-branch revision 273027] binutils: (2.35.2-2+14+b2) 2.35.2)
MCU 'adxl' config: ADC_MAX=4095 BUS_PINS_i2c0a=gpio0,gpio1 BUS_PINS_i2c0b=gpio4,gpio5 BUS_PINS_i2c0c=gpio8,gpio9 BUS_PINS_i2c0d=gpio12,gpio13 BUS_PINS_i2c0e=gpio16,gpio17 BUS_PINS_i2c0f=gpio20,gpio21 BUS_PINS_i2c0g=gpio24,gpio25 BUS_PINS_i2c0h=gpio28,gpio29 BUS_PINS_i2c1a=gpio2,gpio3 BUS_PINS_i2c1b=gpio6,gpio7 BUS_PINS_i2c1c=gpio10,gpio11 BUS_PINS_i2c1d=gpio14,gpio15 BUS_PINS_i2c1e=gpio18,gpio19 BUS_PINS_i2c1f=gpio22,gpio23 BUS_PINS_i2c1g=gpio26,gpio27 BUS_PINS_spi0a=gpio0,gpio3,gpio2 BUS_PINS_spi0b=gpio4,gpio7,gpio6 BUS_PINS_spi0c=gpio16,gpio19,gpio18 BUS_PINS_spi0d=gpio20,gpio23,gpio22 BUS_PINS_spi1a=gpio8,gpio11,gpio10 BUS_PINS_spi1b=gpio12,gpio15,gpio14 BUS_PINS_spi1c=gpio24,gpio27,gpio26 CLOCK_FREQ=12000000 MCU=rp2040 PWM_MAX=255 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
Sending MCU 'mcu' printer configuration...
Configured MCU 'mcu' (1024 moves)
Sending MCU 'adxl' printer configuration...
Config error
Traceback (most recent call last):
  File "/home/quadra/klipper/klippy/mcu.py", line 707, in _send_config
    self._serial.send(c)
  File "/home/quadra/klipper/klippy/serialhdl.py", line 256, in send
    cmd = self.msgparser.create_command(msg)
  File "/home/quadra/klipper/klippy/msgproto.py", line 350, in create_command
    cmd = mp.encode_by_name(**argparts)
  File "/home/quadra/klipper/klippy/msgproto.py", line 181, in encode_by_name
    t.encode(out, params[name])
  File "/home/quadra/klipper/klippy/msgproto.py", line 108, in encode
    raise enumeration_error(self.enum_name, v)
msgproto.enumeration_error: Unknown value 'PA4' in enumeration 'pin'

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "/home/quadra/klipper/klippy/klippy.py", line 180, in _connect
    cb()
  File "/home/quadra/klipper/klippy/mcu.py", line 753, in _connect
    self._send_config(None)
  File "/home/quadra/klipper/klippy/mcu.py", line 718, in _send_config
    raise self._printer.config_error(
configparser.Error: Pin 'PA4' is not a valid pin name on mcu 'adxl'
webhooks client 281473353273600: Disconnected
Restarting printer
Start printer at Tue Mar 21 16:14:23 2023 (1679433263.6 8462.3)
===== Config file =====
[mcu adxl]
serial = /dev/serial/by-id/usb-Klipper_rp2040_E6622005435F4132-if00

[adxl345]
cs_pin = adxl:PA4
spi_software_sclk_pin = adxl:PA5
spi_software_mosi_pin = adxl:PA7
spi_software_miso_pin = adxl:PA6

[resonance_tester]
accel_chip = adxl345
probe_points = 
	110,110,20

**Comment by xbst** [comment]
Looks like you downloaded the v1 KUSBA .cfg file instead of v2. Use this config:
https://github.com/xbst/KUSBA/blob/main/Firmware/v2/adxlmcu.cfg

**Comment by plano-harry** [comment]
I will give it a try. Thanks!

**Comment by plano-harry** [comment]
Thanks!  Solved.
