### ISSUE TITLE
KUsba not recognised

### ISSUE THREAD

**Issue by Reneeetje** [xbst/KUSBA#24]
My raspberry pi 3 recognised the Kusba, my pi 4 does not, if i mount it and cp firmware, that is all ok on the pi 4, but afther reboot not recognised.

var/log
>
Jul  9 12:58:53 ender5plus mtp-probe: bus: 1, device: 5 was not an MTP device
Jul  9 13:06:23 ender5plus kernel: [  735.467182] usb 1-1.2: USB disconnect, device number 5
Jul  9 13:21:49 ender5plus kernel: [ 1661.520531] usb 1-1.2: new full-speed USB device number 6 using xhci_hcd
Jul  9 13:21:49 ender5plus kernel: [ 1661.632498] usb 1-1.2: New USB device found, idVendor=1d50, idProduct=614e, bcdDevice>
Jul  9 13:21:49 ender5plus kernel: [ 1661.632532] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul  9 13:21:49 ender5plus kernel: [ 1661.632547] usb 1-1.2: Product: Rampon
Jul  9 13:21:49 ender5plus kernel: [ 1661.632559] usb 1-1.2: Manufacturer: Anchor
Jul  9 13:21:49 ender5plus kernel: [ 1661.638559] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
Jul  9 13:21:49 ender5plus mtp-probe: checking bus 1, device 6: "/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00>
Jul  9 13:21:49 ender5plus mtp-probe: bus: 1, device: 6 was not an MTP device
Jul  9 13:21:49 ender5plus mtp-probe: checking bus 1, device 6: "/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00>
Jul  9 13:21:49 ender5plus mtp-probe: bus: 1, device: 6 was not an MTP device
Jul  9 13:23:14 ender5plus mtp-probe: checking bus 1, device 4: "/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00>
Jul  9 13:23:14 ender5plus mtp-probe: bus: 1, device: 4 was not an MTP device
Jul  9 13:23:14 ender5plus mtp-probe: checking bus 1, device 3: "/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00>
Jul  9 13:23:14 ender5plus mtp-probe: bus: 1, device: 3 was not an MTP device

**Comment by xbst** [comment]
So you only get this error on your pi 4 but not pi 3? If so it sounds like the problem is on your pi 4. I'm not really a Linux expert so I'm not sure if I can help with this.
