### ISSUE TITLE
Downloading adxlmcu.cfg file on Windows 11 messes up formatting

### ISSUE THREAD

**Issue by charminULTRA** [xbst/KUSBA#32]
Within: https://github.com/xbst/KUSBA/blob/main/Docs/v2-Rampon-Firmware.md

"Download the [adxlmcu.cfg](https://github.com/xbst/KUSBA/blob/main/Firmware/v2-Rampon/adxlmcu.cfg) file from this repo and add it to your Klipper config directory."

I did this, and used the web interface on Mainsail to upload the file, without any editing, and the text wrapping was completely gone, and it's very hard to read. Instead I just copy pasted the real file contents. I'd recommend a warning in the instructions for PC users.

When I upload it into Mainsail, the file contents are, so something seems very wrong.

`{"payload":{"allShortcutsEnabled":true,"fileTree":{"Firmware/v2-Rampon":{"items":[{"name":"adxlmcu.cfg","path":"Firmware/v2-Rampon/adxlmcu.cfg","contentType":"file"}],"totalCount":1},"Firmware":{"items":[{"name":"v1","path":"Firmware/v1","contentType":"directory"},{"name":"v2-Rampon","path":"Firmware/v2-Rampon","contentType":"directory"},{"name":"v2","path":"Firmware/v2","contentType":"directory"}],"totalCount":3},"":{"items":[{"name":".github","path":".github","contentType":"directory"},{"name":"CAD","path":"CAD","contentType":"directory"},{"name":"Docs","path":"Docs","contentType":"directory"},{"name":"EasyEDA-Source","path":"EasyEDA-Source","contentType":"directory"},{"name":"Firmware","path":"Firmware","contentType":"directory"},{"name":"Gerbers","path":"Gerbers","contentType":"directory"},{"name":"Images","path":"Images","contentType":"directory"},{"name":"Mounts","path":"Mounts","contentType":"directory"},{"name":"LICENSE","path":"LICENSE","contentType":"file"},{"name":"README.md","path":"README.md","contentType":"file"}],"totalCount":10}},"fileTreeProcessingTime":4.750375,"foldersToFetch":[],"repo":{"id":478221104,"defaultBranch":"main","name":"KUSBA","ownerLogin":"xbst","currentUserCanPush":false,"isFork":false,"isEmpty":false,"createdAt":"2022-04-05T12:53:06.000-04:00","ownerAvatar":"https://avatars.githubusercontent.com/u/62180989?v=4","public":true,"private":false,"isOrgOwned":false},"symbolsExpanded":true,"treeExpanded":true,"refInfo":{"name":"main","listCacheKey":"v0:1686083309.607299","canEdit":true,"refType":"branch","currentOid":"1437d9c7ae85217e4cb4974874b8482226edf2ec"},"path":"Firmware/v2-Rampon/adxlmcu.cfg","currentUser":{"id":29433007,"login":"charminULTRA","userEmail":"jcw122@gmail.com"},"blob":{"rawLines":["[mcu adxl]","serial: /dev/serial/by-id/usb-Anchor_Rampon-if00","","[adxl345]","cs_pin: adxl:CS","","[resonance_tester]","accel_chip: adxl345","probe_points:","   0,0,0","# Edit the above line with the correct probe points location. I recommend the center of your bed for X & Y, 20 for Z.","# For 350 mm printers: 175,175,20","# For 300 mm printers: 150,150,20","# For 250 mm printers: 125,125,20","# For 120 mm printers: 60,60,20","","# More info: https://www.klipper3d.org/Config_Reference.html#adxl345"],"stylingDirectives":[[{"start":0,"end":10,"cssClass":"pl-en"}],[],[],[{"start":0,"end":9,"cssClass":"pl-en"}],[],[],[{"start":0,"end":18,"cssClass":"pl-en"}],[],[],[],[{"start":0,"end":117,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}],[{"start":0,"end":33,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}],[{"start":0,"end":33,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}],[{"start":0,"end":33,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}],[{"start":0,"end":31,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}],[],[{"start":0,"end":68,"cssClass":"pl-c"},{"start":0,"end":1,"cssClass":"pl-c"}]],"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":false,"configFilePath":null,"networkDependabotPath":"/xbst/KUSBA/network/updates","dismissConfigurationNoticePath":"/settings/dismiss-notice/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"/xbst/KUSBA/security/dependabot","repoSecurityAndAnalysisPath":"/xbst/KUSBA/settings/security_analysis","repoOwnerIsOrg":false,"currentUserCanAdminRepo":false},"displayName":"adxlmcu.cfg","displayUrl":"https://github.com/xbst/KUSBA/blob/main/Firmware/v2-Rampon/adxlmcu.cfg?raw=true","headerInfo":{"blobSize":"472 Bytes","deleteInfo":{"deleteTooltip":"Fork this repository and delete the file"},"editInfo":{"editTooltip":"Fork this repository and edit the file"},"ghDesktopPath":"x-github-client://openRepo/https://github.com/xbst/KUSBA?branch=main&filepath=Firmware%2Fv2-Rampon%2Fadxlmcu.cfg","gitLfsPath":null,"onBranch":true,"shortPath":"183f14f","siteNavLoginPath":"/login?return_to=https%3A%2F%2Fgithub.com%2Fxbst%2FKUSBA%2Fblob%2Fmain%2FFirmware%2Fv2-Rampon%2Fadxlmcu.cfg","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":{"truncatedLoc":"17","truncatedSloc":"14"},"mode":"file"},"image":false,"isCodeownersFile":null,"isPlain":false,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https://docs.github.com/articles/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":"INI","languageID":163,"large":false,"loggedIn":true,"newDiscussionPath":"/xbst/KUSBA/discussions/new","newIssuePath":"/xbst/KUSBA/issues/new","planSupportInfo":{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"/xbst/KUSBA/blob/main/Firmware/v2-Rampon/adxlmcu.cfg","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null},"publishBannersInfo":{"dismissActionNoticePath":"/settings/dismiss-notice/publish_action_from_dockerfile","releasePath":"/xbst/KUSBA/releases/new?marketplace=true","showPublishActionBanner":false},"rawBlobUrl":"https://github.com/xbst/KUSBA/raw/main/Firmware/v2-Rampon/adxlmcu.cfg","renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"shortPath":null,"symbolsEnabled":true,"tabSize":8,"topBannersInfo":{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"xbst","repoName":"KUSBA","showInvalidCitationWarning":false,"citationHelpUrl":"https://docs.github.com/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files","showDependabotConfigurationBanner":false,"actionsOnboardingTip":null},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":{"timed_out":false,"not_analyzed":true,"symbols":[]}},"copilotInfo":null,"copilotAccessAllowed":false,"csrf_tokens":{"/xbst/KUSBA/branches":{"post":"AfkwcHjskUNBSYJ-77nCRbPRc3g_Qj3leOir6nac9FHi8Y7AcIAeL7VTGTjh9zBLSt0jN6zoBlIVuVHxHFUCWA"},"/repos/preferences":{"post":"wg8g0YKe21jTvDGIP2mks0hwvvyUAm392O7qaGnqy7_We9lngC3Ul8veuDlZDPG3P5EmzaOHY3E4SYYEQ5AcrQ"}}},"title":"KUSBA/Firmware/v2-Rampon/adxlmcu.cfg at main · xbst/KUSBA"}`

**Comment by xbst** [comment]
I just downloaded this file and it downloaded just fine. Most people download this file on Windows and upload using Mainsail without any problems. Are you sure you didn't download page source or something like that instead of the raw file?

**Comment by charminULTRA** [comment]
I right clicked the link and hit Save Link As, which is a typical action
for Windows to save things in their current format. Left clicking the link
brought me to the GitHub page of the file contents which isn’t what I
wanted or expected.

**Comment by charminULTRA** [comment]
> I just downloaded this file and it downloaded just fine. Most people download this file on Windows and upload using Mainsail without any problems. Are you sure you didn't download page source or something like that instead of the raw file?

Following up here, when using the Download button on this page linked, it works fine: https://github.com/xbst/KUSBA/blob/main/Firmware/v2-Rampon/adxlmcu.cfg I can't explain why this doesn't work the same as Save Link As.

**Comment by xbst** [comment]
It's because "save link as" saves the entire page, not just the file. So it includes everything you see when you click that link (GitHub logo, buttons, etc.) instead of just that file.
