### ISSUE TITLE
M6 Mount Issue

### ISSUE THREAD

**Issue by charminULTRA** [xbst/KUSBA#34]
https://github.com/xbst/KUSBA/blob/main/Mounts/M6_KUSBA_Mount.stl

The screw holes in the mount are larger than the screw holes in the KUSBA, therefore not mountable. The screws that fit the mount won't go through the KUSBA holes because they're too big.

**Comment by xbst** [comment]
They're for M3 threaded inserts.

**Comment by charminULTRA** [comment]
Oh ok, the instructions didn’t mention that.
