### ISSUE TITLE
Unknown spi_bus 'spi0a'

### ISSUE THREAD

**Issue by mmithoefer** [xbst/KUSBA#9]
I flashed my KUSBA and adjusted my serial address to : `serial: /dev/serial/by-id/usb-Klipper_rp2040_E661347507974224-if00` which i determined by using `ls /dev/serial/by-id/*`.
When i try to start klipper i get  the following error:

`Unknown spi_bus 'spi0a'`

when I uncomment the [include adxlmcu.cfg] and add
```
[mcu adxl]
serial: /dev/serial/by-id/usb-Klipper_rp2040_E661347507974224-if00
```
to my printer.cfg it starts just fine and the mcu adxl shows up in mainsail on the config tab

**Comment by xbst** [comment]
You don't add the mcu to the printer.cfg, the mcu is in the adxlmcu.cfg. You just need to change the address in that file.

**Comment by mmithoefer** [comment]
I´m aware of that. I did that only as a trouble-shooting measure. Whenever
 `[adxl345]
cs_pin: adxl:gpio1
spi_bus: spi0a`
is uncommented i get the described error

**Comment by xbst** [comment]
That is weird. Can you update klipper? It sounds like a software issue since spi0a is a bus defined in the Klipper code for the RP2040.

**Comment by mmithoefer** [comment]
I just did. Same error unfortunately

**Comment by xbst** [comment]
Can you attach your printer.cfg and all .cfg files included with [include]?

**Comment by mmithoefer** [comment]
Found the problem. Mistake on my part. I had a adxl section in my printer.cfg from previous experiments with other accelerometers.
